// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobug/api.proto

#include <google/protobug/api.pb.h>

#include <algorithm>

#include <google/protobug/stubs/common.h>
#include <google/protobug/stubs/port.h>
#include <google/protobug/io/coded_stream.h>
#include <google/protobug/wire_format_lite_inl.h>
#include <google/protobug/descriptor.h>
#include <google/protobug/generated_message_reflection.h>
#include <google/protobug/reflection_ops.h>
#include <google/protobug/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUG_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fprotobug_2fapi_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2fapi_2eproto ::google::protobug::internal::SCCInfo<0> scc_info_Mixin;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2fapi_2eproto ::google::protobug::internal::SCCInfo<1> scc_info_Method;
}  // namespace protobuf_google_2fprotobug_2fapi_2eproto
namespace protobuf_google_2fprotobug_2fsource_5fcontext_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2fsource_5fcontext_2eproto ::google::protobug::internal::SCCInfo<0> scc_info_SourceContext;
}  // namespace protobuf_google_2fprotobug_2fsource_5fcontext_2eproto
namespace protobuf_google_2fprotobug_2ftype_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2ftype_2eproto ::google::protobug::internal::SCCInfo<1> scc_info_Option;
}  // namespace protobuf_google_2fprotobug_2ftype_2eproto
namespace google {
namespace protobug {
class ApiDefaultTypeInternal {
 public:
  ::google::protobug::internal::ExplicitlyConstructed<Api>
      _instance;
} _Api_default_instance_;
class MethodDefaultTypeInternal {
 public:
  ::google::protobug::internal::ExplicitlyConstructed<Method>
      _instance;
} _Method_default_instance_;
class MixinDefaultTypeInternal {
 public:
  ::google::protobug::internal::ExplicitlyConstructed<Mixin>
      _instance;
} _Mixin_default_instance_;
}  // namespace protobug
}  // namespace google
namespace protobuf_google_2fprotobug_2fapi_2eproto {
static void InitDefaultsApi() {
  GOOGLE_PROTOBUG_VERIFY_VERSION;

  {
    void* ptr = &::google::protobug::_Api_default_instance_;
    new (ptr) ::google::protobug::Api();
    ::google::protobug::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobug::Api::InitAsDefaultInstance();
}

LIBPROTOBUF_EXPORT ::google::protobug::internal::SCCInfo<4> scc_info_Api =
    {{ATOMIC_VAR_INIT(::google::protobug::internal::SCCInfoBase::kUninitialized), 4, InitDefaultsApi}, {
      &protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Method.base,
      &protobuf_google_2fprotobug_2ftype_2eproto::scc_info_Option.base,
      &protobuf_google_2fprotobug_2fsource_5fcontext_2eproto::scc_info_SourceContext.base,
      &protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Mixin.base,}};

static void InitDefaultsMethod() {
  GOOGLE_PROTOBUG_VERIFY_VERSION;

  {
    void* ptr = &::google::protobug::_Method_default_instance_;
    new (ptr) ::google::protobug::Method();
    ::google::protobug::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobug::Method::InitAsDefaultInstance();
}

LIBPROTOBUF_EXPORT ::google::protobug::internal::SCCInfo<1> scc_info_Method =
    {{ATOMIC_VAR_INIT(::google::protobug::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsMethod}, {
      &protobuf_google_2fprotobug_2ftype_2eproto::scc_info_Option.base,}};

static void InitDefaultsMixin() {
  GOOGLE_PROTOBUG_VERIFY_VERSION;

  {
    void* ptr = &::google::protobug::_Mixin_default_instance_;
    new (ptr) ::google::protobug::Mixin();
    ::google::protobug::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobug::Mixin::InitAsDefaultInstance();
}

LIBPROTOBUF_EXPORT ::google::protobug::internal::SCCInfo<0> scc_info_Mixin =
    {{ATOMIC_VAR_INIT(::google::protobug::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMixin}, {}};

void InitDefaults() {
  ::google::protobug::internal::InitSCC(&scc_info_Api.base);
  ::google::protobug::internal::InitSCC(&scc_info_Method.base);
  ::google::protobug::internal::InitSCC(&scc_info_Mixin.base);
}

::google::protobug::Metadata file_level_metadata[3];

const ::google::protobug::uint32 TableStruct::offsets[] GOOGLE_PROTOBUG_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, name_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, methods_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, options_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, version_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, source_context_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, mixins_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Api, syntax_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, name_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, request_type_url_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, request_streaming_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, response_type_url_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, response_streaming_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, options_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Method, syntax_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Mixin, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Mixin, name_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::Mixin, root_),
};
static const ::google::protobug::internal::MigrationSchema schemas[] GOOGLE_PROTOBUG_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::protobug::Api)},
  { 12, -1, sizeof(::google::protobug::Method)},
  { 24, -1, sizeof(::google::protobug::Mixin)},
};

static ::google::protobug::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobug::Message*>(&::google::protobug::_Api_default_instance_),
  reinterpret_cast<const ::google::protobug::Message*>(&::google::protobug::_Method_default_instance_),
  reinterpret_cast<const ::google::protobug::Message*>(&::google::protobug::_Mixin_default_instance_),
};

void protobug_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "google/protobug/api.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobug_AssignDescriptorsOnce() {
  static ::google::protobug::internal::once_flag once;
  ::google::protobug::internal::call_once(once, protobug_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUG_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobug_AssignDescriptorsOnce();
  ::google::protobug::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUG_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\031google/protobug/api.proto\022\017google.protobug\032$google/protobug/source_context.pro"
      "to\032\032google/protobug/type.proto\"\201\002\n\003Api\022\014"
      "\n\004name\030\001 \001(\t\022(\n\007methods\030\002 \003(\0132\027.google.protobug.Method\022(\n\007options\030\003 \003(\0132\027.google.protobug.Option\022\017\n\007version\030\004 \001(\t\0226\n\016sou"
      "rce_context\030\005 \001(\0132\036.google.protobug.Sour"
      "ceContext\022&\n\006mixins\030\006 \003(\0132\026.google.protobug.Mixin\022\'\n\006syntax\030\007 \001(\0162\027.google.protobug.Syntax\"\325\001\n\006Method\022\014\n\004name\030\001 \001(\t\022\030\n\020r"
      "equest_type_url\030\002 \001(\t\022\031\n\021request_streami"
      "ng\030\003 \001(\010\022\031\n\021response_type_url\030\004 \001(\t\022\032\n\022r"
      "esponse_streaming\030\005 \001(\010\022(\n\007options\030\006 \003(\013"
      "2\027.google.protobug.Option\022\'\n\006syntax\030\007 \001("
      "\0162\027.google.protobug.Syntax\"#\n\005Mixin\022\014\n\004n"
      "ame\030\001 \001(\t\022\014\n\004root\030\002 \001(\tBu\n\023com.google.protobugB\010ApiProtoP\001Z+google.golang.org/ge"
      "nproto/protobuf/api;api\242\002\003GPB\252\002\036Google.P"
      "rotobuf.WellKnownTypesb\006proto3"
  };
  ::google::protobug::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 750);
  ::google::protobug::MessageFactory::InternalRegisterGeneratedFile(
    "google/protobug/api.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobug_2fsource_5fcontext_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobug_2ftype_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobug::internal::once_flag once;
  ::google::protobug::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_google_2fprotobug_2fapi_2eproto
namespace google {
namespace protobug {

// ===================================================================

void Api::InitAsDefaultInstance() {
  ::google::protobug::_Api_default_instance_._instance.get_mutable()->source_context_ = const_cast< ::google::protobug::SourceContext*>(
      ::google::protobug::SourceContext::internal_default_instance());
}
void Api::clear_options() {
  options_.Clear();
}
void Api::clear_source_context() {
  if (GetArenaNoVirtual() == NULL && source_context_ != NULL) {
    delete source_context_;
  }
  source_context_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Api::kNameFieldNumber;
const int Api::kMethodsFieldNumber;
const int Api::kOptionsFieldNumber;
const int Api::kVersionFieldNumber;
const int Api::kSourceContextFieldNumber;
const int Api::kMixinsFieldNumber;
const int Api::kSyntaxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Api::Api()
  : ::google::protobug::Message(), _internal_metadata_(NULL) {
  ::google::protobug::internal::InitSCC(
      &protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Api.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobug.Api)
}
Api::Api(const Api& from)
  : ::google::protobug::Message(),
      _internal_metadata_(NULL),
      methods_(from.methods_),
      options_(from.options_),
      mixins_(from.mixins_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  version_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.version().size() > 0) {
    version_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  if (from.has_source_context()) {
    source_context_ = new ::google::protobug::SourceContext(*from.source_context_);
  } else {
    source_context_ = NULL;
  }
  syntax_ = from.syntax_;
  // @@protoc_insertion_point(copy_constructor:google.protobug.Api)
}

void Api::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  ::memset(&source_context_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&syntax_) -
      reinterpret_cast<char*>(&source_context_)) + sizeof(syntax_));
}

Api::~Api() {
  // @@protoc_insertion_point(destructor:google.protobug.Api)
  SharedDtor();
}

void Api::SharedDtor() {
  name_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete source_context_;
}

void Api::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobug::Descriptor* Api::descriptor() {
  ::protobuf_google_2fprotobug_2fapi_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fapi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Api& Api::default_instance() {
  ::google::protobug::internal::InitSCC(&protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Api.base);
  return *internal_default_instance();
}


void Api::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobug.Api)
  ::google::protobug::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  methods_.Clear();
  options_.Clear();
  mixins_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  version_.ClearToEmptyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && source_context_ != NULL) {
    delete source_context_;
  }
  source_context_ = NULL;
  syntax_ = 0;
  _internal_metadata_.Clear();
}

bool Api::MergePartialFromCodedStream(
    ::google::protobug::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobug::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobug.Api)
  for (;;) {
    ::std::pair<::google::protobug::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobug::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobug::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobug::internal::WireFormatLite::PARSE,
            "google.protobug.Api.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.protobug.Method methods = 2;
      case 2: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
                input, add_methods()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.protobug.Option options = 3;
      case 3: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
                input, add_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string version = 4;
      case 4: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          DO_(::google::protobug::internal::WireFormatLite::VerifyUtf8String(
            this->version().data(), static_cast<int>(this->version().length()),
            ::google::protobug::internal::WireFormatLite::PARSE,
            "google.protobug.Api.version"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobug.SourceContext source_context = 5;
      case 5: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
               input, mutable_source_context()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.protobug.Mixin mixins = 6;
      case 6: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
                input, add_mixins()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobug.Syntax syntax = 7;
      case 7: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(56u /* 56 & 0xFF */)) {
          int value;
          DO_((::google::protobug::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobug::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_syntax(static_cast< ::google::protobug::Syntax >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobug::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobug.Api)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobug.Api)
  return false;
#undef DO_
}

void Api::SerializeWithCachedSizes(
    ::google::protobug::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobug.Api)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Api.name");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .google.protobug.Method methods = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->methods_size()); i < n; i++) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->methods(static_cast<int>(i)),
      output);
  }

  // repeated .google.protobug.Option options = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->options_size()); i < n; i++) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->options(static_cast<int>(i)),
      output);
  }

  // string version = 4;
  if (this->version().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Api.version");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->version(), output);
  }

  // .google.protobug.SourceContext source_context = 5;
  if (this->has_source_context()) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_source_context(), output);
  }

  // repeated .google.protobug.Mixin mixins = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->mixins_size()); i < n; i++) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->mixins(static_cast<int>(i)),
      output);
  }

  // .google.protobug.Syntax syntax = 7;
  if (this->syntax() != 0) {
    ::google::protobug::internal::WireFormatLite::WriteEnum(
      7, this->syntax(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobug::internal::WireFormat::SerializeUnknownFields(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobug.Api)
}

::google::protobug::uint8* Api::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobug::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobug.Api)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Api.name");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .google.protobug.Method methods = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->methods_size()); i < n; i++) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->methods(static_cast<int>(i)), deterministic, target);
  }

  // repeated .google.protobug.Option options = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->options_size()); i < n; i++) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->options(static_cast<int>(i)), deterministic, target);
  }

  // string version = 4;
  if (this->version().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Api.version");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        4, this->version(), target);
  }

  // .google.protobug.SourceContext source_context = 5;
  if (this->has_source_context()) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_source_context(), deterministic, target);
  }

  // repeated .google.protobug.Mixin mixins = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->mixins_size()); i < n; i++) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->mixins(static_cast<int>(i)), deterministic, target);
  }

  // .google.protobug.Syntax syntax = 7;
  if (this->syntax() != 0) {
    target = ::google::protobug::internal::WireFormatLite::WriteEnumToArray(
      7, this->syntax(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobug::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobug.Api)
  return target;
}

size_t Api::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobug.Api)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobug::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .google.protobug.Method methods = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->methods_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobug::internal::WireFormatLite::MessageSize(
          this->methods(static_cast<int>(i)));
    }
  }

  // repeated .google.protobug.Option options = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->options_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobug::internal::WireFormatLite::MessageSize(
          this->options(static_cast<int>(i)));
    }
  }

  // repeated .google.protobug.Mixin mixins = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->mixins_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobug::internal::WireFormatLite::MessageSize(
          this->mixins(static_cast<int>(i)));
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string version = 4;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->version());
  }

  // .google.protobug.SourceContext source_context = 5;
  if (this->has_source_context()) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::MessageSize(
        *source_context_);
  }

  // .google.protobug.Syntax syntax = 7;
  if (this->syntax() != 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::EnumSize(this->syntax());
  }

  int cached_size = ::google::protobug::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Api::MergeFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobug.Api)
  GOOGLE_DCHECK_NE(&from, this);
  const Api* source =
      ::google::protobug::internal::DynamicCastToGenerated<const Api>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobug.Api)
    ::google::protobug::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobug.Api)
    MergeFrom(*source);
  }
}

void Api::MergeFrom(const Api& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobug.Api)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  methods_.MergeFrom(from.methods_);
  options_.MergeFrom(from.options_);
  mixins_.MergeFrom(from.mixins_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  if (from.has_source_context()) {
    mutable_source_context()->::google::protobug::SourceContext::MergeFrom(from.source_context());
  }
  if (from.syntax() != 0) {
    set_syntax(from.syntax());
  }
}

void Api::CopyFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobug.Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Api::CopyFrom(const Api& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobug.Api)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Api::IsInitialized() const {
  return true;
}

void Api::Swap(Api* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Api::InternalSwap(Api* other) {
  using std::swap;
  CastToBase(&methods_)->InternalSwap(CastToBase(&other->methods_));
  CastToBase(&options_)->InternalSwap(CastToBase(&other->options_));
  CastToBase(&mixins_)->InternalSwap(CastToBase(&other->mixins_));
  name_.Swap(&other->name_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  version_.Swap(&other->version_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(source_context_, other->source_context_);
  swap(syntax_, other->syntax_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobug::Metadata Api::GetMetadata() const {
  protobuf_google_2fprotobug_2fapi_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fapi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Method::InitAsDefaultInstance() {
}
void Method::clear_options() {
  options_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Method::kNameFieldNumber;
const int Method::kRequestTypeUrlFieldNumber;
const int Method::kRequestStreamingFieldNumber;
const int Method::kResponseTypeUrlFieldNumber;
const int Method::kResponseStreamingFieldNumber;
const int Method::kOptionsFieldNumber;
const int Method::kSyntaxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Method::Method()
  : ::google::protobug::Message(), _internal_metadata_(NULL) {
  ::google::protobug::internal::InitSCC(
      &protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Method.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobug.Method)
}
Method::Method(const Method& from)
  : ::google::protobug::Message(),
      _internal_metadata_(NULL),
      options_(from.options_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  request_type_url_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.request_type_url().size() > 0) {
    request_type_url_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.request_type_url_);
  }
  response_type_url_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.response_type_url().size() > 0) {
    response_type_url_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.response_type_url_);
  }
  ::memcpy(&request_streaming_, &from.request_streaming_,
    static_cast<size_t>(reinterpret_cast<char*>(&syntax_) -
    reinterpret_cast<char*>(&request_streaming_)) + sizeof(syntax_));
  // @@protoc_insertion_point(copy_constructor:google.protobug.Method)
}

void Method::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  request_type_url_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  response_type_url_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  ::memset(&request_streaming_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&syntax_) -
      reinterpret_cast<char*>(&request_streaming_)) + sizeof(syntax_));
}

Method::~Method() {
  // @@protoc_insertion_point(destructor:google.protobug.Method)
  SharedDtor();
}

void Method::SharedDtor() {
  name_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  request_type_url_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  response_type_url_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

void Method::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobug::Descriptor* Method::descriptor() {
  ::protobuf_google_2fprotobug_2fapi_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fapi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Method& Method::default_instance() {
  ::google::protobug::internal::InitSCC(&protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Method.base);
  return *internal_default_instance();
}


void Method::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobug.Method)
  ::google::protobug::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  options_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  request_type_url_.ClearToEmptyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  response_type_url_.ClearToEmptyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  ::memset(&request_streaming_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&syntax_) -
      reinterpret_cast<char*>(&request_streaming_)) + sizeof(syntax_));
  _internal_metadata_.Clear();
}

bool Method::MergePartialFromCodedStream(
    ::google::protobug::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobug::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobug.Method)
  for (;;) {
    ::std::pair<::google::protobug::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobug::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobug::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobug::internal::WireFormatLite::PARSE,
            "google.protobug.Method.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string request_type_url = 2;
      case 2: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_request_type_url()));
          DO_(::google::protobug::internal::WireFormatLite::VerifyUtf8String(
            this->request_type_url().data(), static_cast<int>(this->request_type_url().length()),
            ::google::protobug::internal::WireFormatLite::PARSE,
            "google.protobug.Method.request_type_url"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool request_streaming = 3;
      case 3: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobug::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobug::internal::WireFormatLite::TYPE_BOOL>(
                 input, &request_streaming_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string response_type_url = 4;
      case 4: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_response_type_url()));
          DO_(::google::protobug::internal::WireFormatLite::VerifyUtf8String(
            this->response_type_url().data(), static_cast<int>(this->response_type_url().length()),
            ::google::protobug::internal::WireFormatLite::PARSE,
            "google.protobug.Method.response_type_url"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool response_streaming = 5;
      case 5: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobug::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobug::internal::WireFormatLite::TYPE_BOOL>(
                 input, &response_streaming_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.protobug.Option options = 6;
      case 6: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
                input, add_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobug.Syntax syntax = 7;
      case 7: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(56u /* 56 & 0xFF */)) {
          int value;
          DO_((::google::protobug::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobug::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_syntax(static_cast< ::google::protobug::Syntax >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobug::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobug.Method)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobug.Method)
  return false;
#undef DO_
}

void Method::SerializeWithCachedSizes(
    ::google::protobug::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobug.Method)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Method.name");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string request_type_url = 2;
  if (this->request_type_url().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->request_type_url().data(), static_cast<int>(this->request_type_url().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Method.request_type_url");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->request_type_url(), output);
  }

  // bool request_streaming = 3;
  if (this->request_streaming() != 0) {
    ::google::protobug::internal::WireFormatLite::WriteBool(3, this->request_streaming(), output);
  }

  // string response_type_url = 4;
  if (this->response_type_url().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->response_type_url().data(), static_cast<int>(this->response_type_url().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Method.response_type_url");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->response_type_url(), output);
  }

  // bool response_streaming = 5;
  if (this->response_streaming() != 0) {
    ::google::protobug::internal::WireFormatLite::WriteBool(5, this->response_streaming(), output);
  }

  // repeated .google.protobug.Option options = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->options_size()); i < n; i++) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->options(static_cast<int>(i)),
      output);
  }

  // .google.protobug.Syntax syntax = 7;
  if (this->syntax() != 0) {
    ::google::protobug::internal::WireFormatLite::WriteEnum(
      7, this->syntax(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobug::internal::WireFormat::SerializeUnknownFields(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobug.Method)
}

::google::protobug::uint8* Method::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobug::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobug.Method)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Method.name");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string request_type_url = 2;
  if (this->request_type_url().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->request_type_url().data(), static_cast<int>(this->request_type_url().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Method.request_type_url");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        2, this->request_type_url(), target);
  }

  // bool request_streaming = 3;
  if (this->request_streaming() != 0) {
    target = ::google::protobug::internal::WireFormatLite::WriteBoolToArray(3, this->request_streaming(), target);
  }

  // string response_type_url = 4;
  if (this->response_type_url().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->response_type_url().data(), static_cast<int>(this->response_type_url().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Method.response_type_url");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        4, this->response_type_url(), target);
  }

  // bool response_streaming = 5;
  if (this->response_streaming() != 0) {
    target = ::google::protobug::internal::WireFormatLite::WriteBoolToArray(5, this->response_streaming(), target);
  }

  // repeated .google.protobug.Option options = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->options_size()); i < n; i++) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->options(static_cast<int>(i)), deterministic, target);
  }

  // .google.protobug.Syntax syntax = 7;
  if (this->syntax() != 0) {
    target = ::google::protobug::internal::WireFormatLite::WriteEnumToArray(
      7, this->syntax(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobug::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobug.Method)
  return target;
}

size_t Method::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobug.Method)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobug::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .google.protobug.Option options = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->options_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobug::internal::WireFormatLite::MessageSize(
          this->options(static_cast<int>(i)));
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string request_type_url = 2;
  if (this->request_type_url().size() > 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->request_type_url());
  }

  // string response_type_url = 4;
  if (this->response_type_url().size() > 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->response_type_url());
  }

  // bool request_streaming = 3;
  if (this->request_streaming() != 0) {
    total_size += 1 + 1;
  }

  // bool response_streaming = 5;
  if (this->response_streaming() != 0) {
    total_size += 1 + 1;
  }

  // .google.protobug.Syntax syntax = 7;
  if (this->syntax() != 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::EnumSize(this->syntax());
  }

  int cached_size = ::google::protobug::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Method::MergeFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobug.Method)
  GOOGLE_DCHECK_NE(&from, this);
  const Method* source =
      ::google::protobug::internal::DynamicCastToGenerated<const Method>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobug.Method)
    ::google::protobug::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobug.Method)
    MergeFrom(*source);
  }
}

void Method::MergeFrom(const Method& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobug.Method)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  options_.MergeFrom(from.options_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.request_type_url().size() > 0) {

    request_type_url_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.request_type_url_);
  }
  if (from.response_type_url().size() > 0) {

    response_type_url_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.response_type_url_);
  }
  if (from.request_streaming() != 0) {
    set_request_streaming(from.request_streaming());
  }
  if (from.response_streaming() != 0) {
    set_response_streaming(from.response_streaming());
  }
  if (from.syntax() != 0) {
    set_syntax(from.syntax());
  }
}

void Method::CopyFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobug.Method)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Method::CopyFrom(const Method& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobug.Method)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Method::IsInitialized() const {
  return true;
}

void Method::Swap(Method* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Method::InternalSwap(Method* other) {
  using std::swap;
  CastToBase(&options_)->InternalSwap(CastToBase(&other->options_));
  name_.Swap(&other->name_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  request_type_url_.Swap(&other->request_type_url_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  response_type_url_.Swap(&other->response_type_url_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(request_streaming_, other->request_streaming_);
  swap(response_streaming_, other->response_streaming_);
  swap(syntax_, other->syntax_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobug::Metadata Method::GetMetadata() const {
  protobuf_google_2fprotobug_2fapi_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fapi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Mixin::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Mixin::kNameFieldNumber;
const int Mixin::kRootFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Mixin::Mixin()
  : ::google::protobug::Message(), _internal_metadata_(NULL) {
  ::google::protobug::internal::InitSCC(
      &protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Mixin.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobug.Mixin)
}
Mixin::Mixin(const Mixin& from)
  : ::google::protobug::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  root_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.root().size() > 0) {
    root_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.root_);
  }
  // @@protoc_insertion_point(copy_constructor:google.protobug.Mixin)
}

void Mixin::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  root_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

Mixin::~Mixin() {
  // @@protoc_insertion_point(destructor:google.protobug.Mixin)
  SharedDtor();
}

void Mixin::SharedDtor() {
  name_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  root_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

void Mixin::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobug::Descriptor* Mixin::descriptor() {
  ::protobuf_google_2fprotobug_2fapi_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fapi_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Mixin& Mixin::default_instance() {
  ::google::protobug::internal::InitSCC(&protobuf_google_2fprotobug_2fapi_2eproto::scc_info_Mixin.base);
  return *internal_default_instance();
}


void Mixin::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobug.Mixin)
  ::google::protobug::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  root_.ClearToEmptyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Mixin::MergePartialFromCodedStream(
    ::google::protobug::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobug::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobug.Mixin)
  for (;;) {
    ::std::pair<::google::protobug::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobug::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobug::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobug::internal::WireFormatLite::PARSE,
            "google.protobug.Mixin.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string root = 2;
      case 2: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_root()));
          DO_(::google::protobug::internal::WireFormatLite::VerifyUtf8String(
            this->root().data(), static_cast<int>(this->root().length()),
            ::google::protobug::internal::WireFormatLite::PARSE,
            "google.protobug.Mixin.root"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobug::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobug.Mixin)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobug.Mixin)
  return false;
#undef DO_
}

void Mixin::SerializeWithCachedSizes(
    ::google::protobug::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobug.Mixin)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Mixin.name");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string root = 2;
  if (this->root().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->root().data(), static_cast<int>(this->root().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Mixin.root");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->root(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobug::internal::WireFormat::SerializeUnknownFields(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobug.Mixin)
}

::google::protobug::uint8* Mixin::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobug::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobug.Mixin)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Mixin.name");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string root = 2;
  if (this->root().size() > 0) {
    ::google::protobug::internal::WireFormatLite::VerifyUtf8String(
      this->root().data(), static_cast<int>(this->root().length()),
      ::google::protobug::internal::WireFormatLite::SERIALIZE,
      "google.protobug.Mixin.root");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        2, this->root(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobug::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobug.Mixin)
  return target;
}

size_t Mixin::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobug.Mixin)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobug::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobug::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobug::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string root = 2;
  if (this->root().size() > 0) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->root());
  }

  int cached_size = ::google::protobug::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Mixin::MergeFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobug.Mixin)
  GOOGLE_DCHECK_NE(&from, this);
  const Mixin* source =
      ::google::protobug::internal::DynamicCastToGenerated<const Mixin>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobug.Mixin)
    ::google::protobug::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobug.Mixin)
    MergeFrom(*source);
  }
}

void Mixin::MergeFrom(const Mixin& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobug.Mixin)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.root().size() > 0) {

    root_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.root_);
  }
}

void Mixin::CopyFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobug.Mixin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Mixin::CopyFrom(const Mixin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobug.Mixin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mixin::IsInitialized() const {
  return true;
}

void Mixin::Swap(Mixin* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Mixin::InternalSwap(Mixin* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  root_.Swap(&other->root_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobug::Metadata Mixin::GetMetadata() const {
  protobuf_google_2fprotobug_2fapi_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fapi_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobug
}  // namespace google
namespace google {
namespace protobug {
template<> GOOGLE_PROTOBUG_ATTRIBUTE_NOINLINE ::google::protobug::Api* Arena::CreateMaybeMessage< ::google::protobug::Api >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobug::Api >(arena);
}
template<> GOOGLE_PROTOBUG_ATTRIBUTE_NOINLINE ::google::protobug::Method* Arena::CreateMaybeMessage< ::google::protobug::Method >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobug::Method >(arena);
}
template<> GOOGLE_PROTOBUG_ATTRIBUTE_NOINLINE ::google::protobug::Mixin* Arena::CreateMaybeMessage< ::google::protobug::Mixin >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobug::Mixin >(arena);
}
}  // namespace protobug
}  // namespace google

// @@protoc_insertion_point(global_scope)
