// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobug/duration.proto

#ifndef PROTOBUF_INCLUDED_google_2fprotobug_2fduration_2eproto
#define PROTOBUF_INCLUDED_google_2fprotobug_2fduration_2eproto

#include <string>

#include <google/protobug/stubs/common.h>

#if GOOGLE_PROTOBUG_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUG_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobug/io/coded_stream.h>
#include <google/protobug/arena.h>
#include <google/protobug/arenastring.h>
#include <google/protobug/generated_message_table_driven.h>
#include <google/protobug/generated_message_util.h>
#include <google/protobug/inlined_string_field.h>
#include <google/protobug/metadata.h>
#include <google/protobug/message.h>
#include <google/protobug/repeated_field.h>  // IWYU pragma: export
#include <google/protobug/extension_set.h>  // IWYU pragma: export
#include <google/protobug/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2fduration_2eproto LIBPROTOBUF_EXPORT

namespace protobuf_google_2fprotobug_2fduration_2eproto {
// Internal implementation detail -- do not use these members.
struct LIBPROTOBUF_EXPORT TableStruct {
  static const ::google::protobug::internal::ParseTableField entries[];
  static const ::google::protobug::internal::AuxillaryParseTableField aux[];
  static const ::google::protobug::internal::ParseTable schema[1];
  static const ::google::protobug::internal::FieldMetadata field_metadata[];
  static const ::google::protobug::internal::SerializationTable serialization_table[];
  static const ::google::protobug::uint32 offsets[];
};
void LIBPROTOBUF_EXPORT AddDescriptors();
}  // namespace protobuf_google_2fprotobug_2fduration_2eproto
namespace google {
namespace protobug {
class Duration;
class DurationDefaultTypeInternal;
LIBPROTOBUF_EXPORT extern DurationDefaultTypeInternal _Duration_default_instance_;
}  // namespace protobug
}  // namespace google
namespace google {
namespace protobug {
template<> LIBPROTOBUF_EXPORT ::google::protobug::Duration* Arena::CreateMaybeMessage<::google::protobug::Duration>(Arena*);
}  // namespace protobug
}  // namespace google
namespace google {
namespace protobug {

// ===================================================================

class LIBPROTOBUF_EXPORT Duration : public ::google::protobug::Message /* @@protoc_insertion_point(class_definition:google.protobug.Duration) */ {
 public:
  Duration();
  virtual ~Duration();

  Duration(const Duration& from);

  inline Duration& operator=(const Duration& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Duration(Duration&& from) noexcept
    : Duration() {
    *this = ::std::move(from);
  }

  inline Duration& operator=(Duration&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobug::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobug::Descriptor* descriptor();
  static const Duration& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Duration* internal_default_instance() {
    return reinterpret_cast<const Duration*>(
               &_Duration_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(Duration* other);
  void Swap(Duration* other);
  friend void swap(Duration& a, Duration& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Duration* New() const final {
    return CreateMaybeMessage<Duration>(NULL);
  }

  Duration* New(::google::protobug::Arena* arena) const final {
    return CreateMaybeMessage<Duration>(arena);
  }
  void CopyFrom(const ::google::protobug::Message& from) final;
  void MergeFrom(const ::google::protobug::Message& from) final;
  void CopyFrom(const Duration& from);
  void MergeFrom(const Duration& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobug::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobug::io::CodedOutputStream* output) const final;
  ::google::protobug::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobug::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Duration* other);
  protected:
  explicit Duration(::google::protobug::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobug::Arena* arena);
  private:
  inline ::google::protobug::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobug::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 seconds = 1;
  void clear_seconds();
  static const int kSecondsFieldNumber = 1;
  ::google::protobug::int64 seconds() const;
  void set_seconds(::google::protobug::int64 value);

  // int32 nanos = 2;
  void clear_nanos();
  static const int kNanosFieldNumber = 2;
  ::google::protobug::int32 nanos() const;
  void set_nanos(::google::protobug::int32 value);

  // @@protoc_insertion_point(class_scope:google.protobug.Duration)
 private:

  ::google::protobug::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobug::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobug::int64 seconds_;
  ::google::protobug::int32 nanos_;
  mutable ::google::protobug::internal::CachedSize _cached_size_;
  friend struct ::protobuf_google_2fprotobug_2fduration_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Duration

// int64 seconds = 1;
inline void Duration::clear_seconds() {
  seconds_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobug::int64 Duration::seconds() const {
  // @@protoc_insertion_point(field_get:google.protobug.Duration.seconds)
  return seconds_;
}
inline void Duration::set_seconds(::google::protobug::int64 value) {
  
  seconds_ = value;
  // @@protoc_insertion_point(field_set:google.protobug.Duration.seconds)
}

// int32 nanos = 2;
inline void Duration::clear_nanos() {
  nanos_ = 0;
}
inline ::google::protobug::int32 Duration::nanos() const {
  // @@protoc_insertion_point(field_get:google.protobug.Duration.nanos)
  return nanos_;
}
inline void Duration::set_nanos(::google::protobug::int32 value) {
  
  nanos_ = value;
  // @@protoc_insertion_point(field_set:google.protobug.Duration.nanos)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobug
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_google_2fprotobug_2fduration_2eproto
