// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobug/compiler/plugin.proto

#include <google/protobug/compiler/plugin.pb.h>

#include <algorithm>

#include <google/protobug/stubs/common.h>
#include <google/protobug/stubs/port.h>
#include <google/protobug/io/coded_stream.h>
#include <google/protobug/wire_format_lite_inl.h>
#include <google/protobug/descriptor.h>
#include <google/protobug/generated_message_reflection.h>
#include <google/protobug/reflection_ops.h>
#include <google/protobug/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUG_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto ::google::protobug::internal::SCCInfo<0> scc_info_CodeGeneratorResponse_File;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto ::google::protobug::internal::SCCInfo<0> scc_info_Version;
}  // namespace protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto
namespace protobuf_google_2fprotobug_2fdescriptor_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobug_2fdescriptor_2eproto ::google::protobug::internal::SCCInfo<6> scc_info_FileDescriptorProto;
}  // namespace protobuf_google_2fprotobug_2fdescriptor_2eproto
namespace google {
namespace protobug {
namespace compiler {
class VersionDefaultTypeInternal {
 public:
  ::google::protobug::internal::ExplicitlyConstructed<Version>
      _instance;
} _Version_default_instance_;
class CodeGeneratorRequestDefaultTypeInternal {
 public:
  ::google::protobug::internal::ExplicitlyConstructed<CodeGeneratorRequest>
      _instance;
} _CodeGeneratorRequest_default_instance_;
class CodeGeneratorResponse_FileDefaultTypeInternal {
 public:
  ::google::protobug::internal::ExplicitlyConstructed<CodeGeneratorResponse_File>
      _instance;
} _CodeGeneratorResponse_File_default_instance_;
class CodeGeneratorResponseDefaultTypeInternal {
 public:
  ::google::protobug::internal::ExplicitlyConstructed<CodeGeneratorResponse>
      _instance;
} _CodeGeneratorResponse_default_instance_;
}  // namespace compiler
}  // namespace protobug
}  // namespace google
namespace protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto {
static void InitDefaultsVersion() {
  GOOGLE_PROTOBUG_VERIFY_VERSION;

  {
    void* ptr = &::google::protobug::compiler::_Version_default_instance_;
    new (ptr) ::google::protobug::compiler::Version();
    ::google::protobug::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobug::compiler::Version::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobug::internal::SCCInfo<0> scc_info_Version =
    {{ATOMIC_VAR_INIT(::google::protobug::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVersion}, {}};

static void InitDefaultsCodeGeneratorRequest() {
  GOOGLE_PROTOBUG_VERIFY_VERSION;

  {
    void* ptr = &::google::protobug::compiler::_CodeGeneratorRequest_default_instance_;
    new (ptr) ::google::protobug::compiler::CodeGeneratorRequest();
    ::google::protobug::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobug::compiler::CodeGeneratorRequest::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobug::internal::SCCInfo<2> scc_info_CodeGeneratorRequest =
    {{ATOMIC_VAR_INIT(::google::protobug::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsCodeGeneratorRequest}, {
      &protobuf_google_2fprotobug_2fdescriptor_2eproto::scc_info_FileDescriptorProto.base,
      &protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_Version.base,}};

static void InitDefaultsCodeGeneratorResponse_File() {
  GOOGLE_PROTOBUG_VERIFY_VERSION;

  {
    void* ptr = &::google::protobug::compiler::_CodeGeneratorResponse_File_default_instance_;
    new (ptr) ::google::protobug::compiler::CodeGeneratorResponse_File();
    ::google::protobug::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobug::compiler::CodeGeneratorResponse_File::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobug::internal::SCCInfo<0> scc_info_CodeGeneratorResponse_File =
    {{ATOMIC_VAR_INIT(::google::protobug::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCodeGeneratorResponse_File}, {}};

static void InitDefaultsCodeGeneratorResponse() {
  GOOGLE_PROTOBUG_VERIFY_VERSION;

  {
    void* ptr = &::google::protobug::compiler::_CodeGeneratorResponse_default_instance_;
    new (ptr) ::google::protobug::compiler::CodeGeneratorResponse();
    ::google::protobug::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobug::compiler::CodeGeneratorResponse::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobug::internal::SCCInfo<1> scc_info_CodeGeneratorResponse =
    {{ATOMIC_VAR_INIT(::google::protobug::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCodeGeneratorResponse}, {
      &protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_CodeGeneratorResponse_File.base,}};

void InitDefaults() {
  ::google::protobug::internal::InitSCC(&scc_info_Version.base);
  ::google::protobug::internal::InitSCC(&scc_info_CodeGeneratorRequest.base);
  ::google::protobug::internal::InitSCC(&scc_info_CodeGeneratorResponse_File.base);
  ::google::protobug::internal::InitSCC(&scc_info_CodeGeneratorResponse.base);
}

::google::protobug::Metadata file_level_metadata[4];

const ::google::protobug::uint32 TableStruct::offsets[] GOOGLE_PROTOBUG_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::Version, _has_bits_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::Version, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::Version, major_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::Version, minor_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::Version, patch_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::Version, suffix_),
  1,
  2,
  3,
  0,
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorRequest, _has_bits_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorRequest, file_to_generate_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorRequest, parameter_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorRequest, proto_file_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorRequest, compiler_version_),
  ~0u,
  0,
  ~0u,
  1,
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse_File, _has_bits_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse_File, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse_File, name_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse_File, insertion_point_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse_File, content_),
  0,
  1,
  2,
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse, _has_bits_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse, error_),
  GOOGLE_PROTOBUG_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobug::compiler::CodeGeneratorResponse, file_),
  0,
  ~0u,
};
static const ::google::protobug::internal::MigrationSchema schemas[] GOOGLE_PROTOBUG_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::google::protobug::compiler::Version)},
  { 13, 22, sizeof(::google::protobug::compiler::CodeGeneratorRequest)},
  { 26, 34, sizeof(::google::protobug::compiler::CodeGeneratorResponse_File)},
  { 37, 44, sizeof(::google::protobug::compiler::CodeGeneratorResponse)},
};

static ::google::protobug::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobug::Message*>(&::google::protobug::compiler::_Version_default_instance_),
  reinterpret_cast<const ::google::protobug::Message*>(&::google::protobug::compiler::_CodeGeneratorRequest_default_instance_),
  reinterpret_cast<const ::google::protobug::Message*>(&::google::protobug::compiler::_CodeGeneratorResponse_File_default_instance_),
  reinterpret_cast<const ::google::protobug::Message*>(&::google::protobug::compiler::_CodeGeneratorResponse_default_instance_),
};

void protobug_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "google/protobug/compiler/plugin.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobug_AssignDescriptorsOnce() {
  static ::google::protobug::internal::once_flag once;
  ::google::protobug::internal::call_once(once, protobug_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUG_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobug_AssignDescriptorsOnce();
  ::google::protobug::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUG_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n%google/protobug/compiler/plugin.proto\022"
      "\030google.protobug.compiler\032 google/protobug/descriptor.proto\"F\n\007Version\022\r\n\005major\030"
      "\001 \001(\005\022\r\n\005minor\030\002 \001(\005\022\r\n\005patch\030\003 \001(\005\022\016\n\006s"
      "uffix\030\004 \001(\t\"\272\001\n\024CodeGeneratorRequest\022\030\n\020"
      "file_to_generate\030\001 \003(\t\022\021\n\tparameter\030\002 \001("
      "\t\0228\n\nproto_file\030\017 \003(\0132$.google.protobug."
      "FileDescriptorProto\022;\n\020compiler_version\030"
      "\003 \001(\0132!.google.protobug.compiler.Version"
      "\"\252\001\n\025CodeGeneratorResponse\022\r\n\005error\030\001 \001("
      "\t\022B\n\004file\030\017 \003(\01324.google.protobug.compil"
      "er.CodeGeneratorResponse.File\032>\n\004File\022\014\n"
      "\004name\030\001 \001(\t\022\027\n\017insertion_point\030\002 \001(\t\022\017\n\007"
      "content\030\017 \001(\tBg\n\034com.google.protobug.com"
      "pilerB\014PluginProtosZ9github.com/golang/p"
      "rotobuf/protoc-gen-go/plugin;plugin_go"
  };
  ::google::protobug::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 638);
  ::google::protobug::MessageFactory::InternalRegisterGeneratedFile(
    "google/protobug/compiler/plugin.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobug_2fdescriptor_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobug::internal::once_flag once;
  ::google::protobug::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto
namespace google {
namespace protobug {
namespace compiler {

// ===================================================================

void Version::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Version::kMajorFieldNumber;
const int Version::kMinorFieldNumber;
const int Version::kPatchFieldNumber;
const int Version::kSuffixFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Version::Version()
  : ::google::protobug::Message(), _internal_metadata_(NULL) {
  ::google::protobug::internal::InitSCC(
      &protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_Version.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobug.compiler.Version)
}
Version::Version(const Version& from)
  : ::google::protobug::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  suffix_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.has_suffix()) {
    suffix_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.suffix_);
  }
  ::memcpy(&major_, &from.major_,
    static_cast<size_t>(reinterpret_cast<char*>(&patch_) -
    reinterpret_cast<char*>(&major_)) + sizeof(patch_));
  // @@protoc_insertion_point(copy_constructor:google.protobug.compiler.Version)
}

void Version::SharedCtor() {
  suffix_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  ::memset(&major_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&patch_) -
      reinterpret_cast<char*>(&major_)) + sizeof(patch_));
}

Version::~Version() {
  // @@protoc_insertion_point(destructor:google.protobug.compiler.Version)
  SharedDtor();
}

void Version::SharedDtor() {
  suffix_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

void Version::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobug::Descriptor* Version::descriptor() {
  ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Version& Version::default_instance() {
  ::google::protobug::internal::InitSCC(&protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_Version.base);
  return *internal_default_instance();
}


void Version::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobug.compiler.Version)
  ::google::protobug::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    suffix_.ClearNonDefaultToEmptyNoArena();
  }
  if (cached_has_bits & 14u) {
    ::memset(&major_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&patch_) -
        reinterpret_cast<char*>(&major_)) + sizeof(patch_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Version::MergePartialFromCodedStream(
    ::google::protobug::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobug::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobug.compiler.Version)
  for (;;) {
    ::std::pair<::google::protobug::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobug::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 major = 1;
      case 1: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(8u /* 8 & 0xFF */)) {
          set_has_major();
          DO_((::google::protobug::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobug::int32, ::google::protobug::internal::WireFormatLite::TYPE_INT32>(
                 input, &major_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 minor = 2;
      case 2: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(16u /* 16 & 0xFF */)) {
          set_has_minor();
          DO_((::google::protobug::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobug::int32, ::google::protobug::internal::WireFormatLite::TYPE_INT32>(
                 input, &minor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 patch = 3;
      case 3: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(24u /* 24 & 0xFF */)) {
          set_has_patch();
          DO_((::google::protobug::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobug::int32, ::google::protobug::internal::WireFormatLite::TYPE_INT32>(
                 input, &patch_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string suffix = 4;
      case 4: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_suffix()));
          ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
            this->suffix().data(), static_cast<int>(this->suffix().length()),
            ::google::protobug::internal::WireFormat::PARSE,
            "google.protobug.compiler.Version.suffix");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobug::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobug.compiler.Version)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobug.compiler.Version)
  return false;
#undef DO_
}

void Version::SerializeWithCachedSizes(
    ::google::protobug::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobug.compiler.Version)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 major = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobug::internal::WireFormatLite::WriteInt32(1, this->major(), output);
  }

  // optional int32 minor = 2;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobug::internal::WireFormatLite::WriteInt32(2, this->minor(), output);
  }

  // optional int32 patch = 3;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobug::internal::WireFormatLite::WriteInt32(3, this->patch(), output);
  }

  // optional string suffix = 4;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->suffix().data(), static_cast<int>(this->suffix().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.Version.suffix");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->suffix(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobug::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobug.compiler.Version)
}

::google::protobug::uint8* Version::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobug::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobug.compiler.Version)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 major = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobug::internal::WireFormatLite::WriteInt32ToArray(1, this->major(), target);
  }

  // optional int32 minor = 2;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobug::internal::WireFormatLite::WriteInt32ToArray(2, this->minor(), target);
  }

  // optional int32 patch = 3;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobug::internal::WireFormatLite::WriteInt32ToArray(3, this->patch(), target);
  }

  // optional string suffix = 4;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->suffix().data(), static_cast<int>(this->suffix().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.Version.suffix");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        4, this->suffix(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobug::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobug.compiler.Version)
  return target;
}

size_t Version::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobug.compiler.Version)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobug::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 15u) {
    // optional string suffix = 4;
    if (has_suffix()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::StringSize(
          this->suffix());
    }

    // optional int32 major = 1;
    if (has_major()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::Int32Size(
          this->major());
    }

    // optional int32 minor = 2;
    if (has_minor()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::Int32Size(
          this->minor());
    }

    // optional int32 patch = 3;
    if (has_patch()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::Int32Size(
          this->patch());
    }

  }
  int cached_size = ::google::protobug::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Version::MergeFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobug.compiler.Version)
  GOOGLE_DCHECK_NE(&from, this);
  const Version* source =
      ::google::protobug::internal::DynamicCastToGenerated<const Version>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobug.compiler.Version)
    ::google::protobug::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobug.compiler.Version)
    MergeFrom(*source);
  }
}

void Version::MergeFrom(const Version& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobug.compiler.Version)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_suffix();
      suffix_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.suffix_);
    }
    if (cached_has_bits & 0x00000002u) {
      major_ = from.major_;
    }
    if (cached_has_bits & 0x00000004u) {
      minor_ = from.minor_;
    }
    if (cached_has_bits & 0x00000008u) {
      patch_ = from.patch_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Version::CopyFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobug.compiler.Version)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Version::CopyFrom(const Version& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobug.compiler.Version)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Version::IsInitialized() const {
  return true;
}

void Version::Swap(Version* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Version::InternalSwap(Version* other) {
  using std::swap;
  suffix_.Swap(&other->suffix_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(major_, other->major_);
  swap(minor_, other->minor_);
  swap(patch_, other->patch_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobug::Metadata Version::GetMetadata() const {
  protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CodeGeneratorRequest::InitAsDefaultInstance() {
  ::google::protobug::compiler::_CodeGeneratorRequest_default_instance_._instance.get_mutable()->compiler_version_ = const_cast< ::google::protobug::compiler::Version*>(
      ::google::protobug::compiler::Version::internal_default_instance());
}
void CodeGeneratorRequest::clear_proto_file() {
  proto_file_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CodeGeneratorRequest::kFileToGenerateFieldNumber;
const int CodeGeneratorRequest::kParameterFieldNumber;
const int CodeGeneratorRequest::kProtoFileFieldNumber;
const int CodeGeneratorRequest::kCompilerVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CodeGeneratorRequest::CodeGeneratorRequest()
  : ::google::protobug::Message(), _internal_metadata_(NULL) {
  ::google::protobug::internal::InitSCC(
      &protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_CodeGeneratorRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobug.compiler.CodeGeneratorRequest)
}
CodeGeneratorRequest::CodeGeneratorRequest(const CodeGeneratorRequest& from)
  : ::google::protobug::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      file_to_generate_(from.file_to_generate_),
      proto_file_(from.proto_file_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  parameter_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.has_parameter()) {
    parameter_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.parameter_);
  }
  if (from.has_compiler_version()) {
    compiler_version_ = new ::google::protobug::compiler::Version(*from.compiler_version_);
  } else {
    compiler_version_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:google.protobug.compiler.CodeGeneratorRequest)
}

void CodeGeneratorRequest::SharedCtor() {
  parameter_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  compiler_version_ = NULL;
}

CodeGeneratorRequest::~CodeGeneratorRequest() {
  // @@protoc_insertion_point(destructor:google.protobug.compiler.CodeGeneratorRequest)
  SharedDtor();
}

void CodeGeneratorRequest::SharedDtor() {
  parameter_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete compiler_version_;
}

void CodeGeneratorRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobug::Descriptor* CodeGeneratorRequest::descriptor() {
  ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CodeGeneratorRequest& CodeGeneratorRequest::default_instance() {
  ::google::protobug::internal::InitSCC(&protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_CodeGeneratorRequest.base);
  return *internal_default_instance();
}


void CodeGeneratorRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobug.compiler.CodeGeneratorRequest)
  ::google::protobug::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  file_to_generate_.Clear();
  proto_file_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      parameter_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(compiler_version_ != NULL);
      compiler_version_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CodeGeneratorRequest::MergePartialFromCodedStream(
    ::google::protobug::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobug::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobug.compiler.CodeGeneratorRequest)
  for (;;) {
    ::std::pair<::google::protobug::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobug::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string file_to_generate = 1;
      case 1: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->add_file_to_generate()));
          ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
            this->file_to_generate(this->file_to_generate_size() - 1).data(),
            static_cast<int>(this->file_to_generate(this->file_to_generate_size() - 1).length()),
            ::google::protobug::internal::WireFormat::PARSE,
            "google.protobug.compiler.CodeGeneratorRequest.file_to_generate");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string parameter = 2;
      case 2: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_parameter()));
          ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
            this->parameter().data(), static_cast<int>(this->parameter().length()),
            ::google::protobug::internal::WireFormat::PARSE,
            "google.protobug.compiler.CodeGeneratorRequest.parameter");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .google.protobug.compiler.Version compiler_version = 3;
      case 3: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
               input, mutable_compiler_version()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.protobug.FileDescriptorProto proto_file = 15;
      case 15: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
                input, add_proto_file()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobug::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobug.compiler.CodeGeneratorRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobug.compiler.CodeGeneratorRequest)
  return false;
#undef DO_
}

void CodeGeneratorRequest::SerializeWithCachedSizes(
    ::google::protobug::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobug.compiler.CodeGeneratorRequest)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string file_to_generate = 1;
  for (int i = 0, n = this->file_to_generate_size(); i < n; i++) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_to_generate(i).data(), static_cast<int>(this->file_to_generate(i).length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorRequest.file_to_generate");
    ::google::protobug::internal::WireFormatLite::WriteString(
      1, this->file_to_generate(i), output);
  }

  cached_has_bits = _has_bits_[0];
  // optional string parameter = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parameter().data(), static_cast<int>(this->parameter().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorRequest.parameter");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->parameter(), output);
  }

  // optional .google.protobug.compiler.Version compiler_version = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_compiler_version(), output);
  }

  // repeated .google.protobug.FileDescriptorProto proto_file = 15;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->proto_file_size()); i < n; i++) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      15,
      this->proto_file(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobug::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobug.compiler.CodeGeneratorRequest)
}

::google::protobug::uint8* CodeGeneratorRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobug::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobug.compiler.CodeGeneratorRequest)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string file_to_generate = 1;
  for (int i = 0, n = this->file_to_generate_size(); i < n; i++) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_to_generate(i).data(), static_cast<int>(this->file_to_generate(i).length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorRequest.file_to_generate");
    target = ::google::protobug::internal::WireFormatLite::
      WriteStringToArray(1, this->file_to_generate(i), target);
  }

  cached_has_bits = _has_bits_[0];
  // optional string parameter = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->parameter().data(), static_cast<int>(this->parameter().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorRequest.parameter");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        2, this->parameter(), target);
  }

  // optional .google.protobug.compiler.Version compiler_version = 3;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_compiler_version(), deterministic, target);
  }

  // repeated .google.protobug.FileDescriptorProto proto_file = 15;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->proto_file_size()); i < n; i++) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        15, this->proto_file(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobug::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobug.compiler.CodeGeneratorRequest)
  return target;
}

size_t CodeGeneratorRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobug.compiler.CodeGeneratorRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobug::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated string file_to_generate = 1;
  total_size += 1 *
      ::google::protobug::internal::FromIntSize(this->file_to_generate_size());
  for (int i = 0, n = this->file_to_generate_size(); i < n; i++) {
    total_size += ::google::protobug::internal::WireFormatLite::StringSize(
      this->file_to_generate(i));
  }

  // repeated .google.protobug.FileDescriptorProto proto_file = 15;
  {
    unsigned int count = static_cast<unsigned int>(this->proto_file_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobug::internal::WireFormatLite::MessageSize(
          this->proto_file(static_cast<int>(i)));
    }
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string parameter = 2;
    if (has_parameter()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::StringSize(
          this->parameter());
    }

    // optional .google.protobug.compiler.Version compiler_version = 3;
    if (has_compiler_version()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::MessageSize(
          *compiler_version_);
    }

  }
  int cached_size = ::google::protobug::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CodeGeneratorRequest::MergeFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobug.compiler.CodeGeneratorRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const CodeGeneratorRequest* source =
      ::google::protobug::internal::DynamicCastToGenerated<const CodeGeneratorRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobug.compiler.CodeGeneratorRequest)
    ::google::protobug::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobug.compiler.CodeGeneratorRequest)
    MergeFrom(*source);
  }
}

void CodeGeneratorRequest::MergeFrom(const CodeGeneratorRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobug.compiler.CodeGeneratorRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  file_to_generate_.MergeFrom(from.file_to_generate_);
  proto_file_.MergeFrom(from.proto_file_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_parameter();
      parameter_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.parameter_);
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_compiler_version()->::google::protobug::compiler::Version::MergeFrom(from.compiler_version());
    }
  }
}

void CodeGeneratorRequest::CopyFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobug.compiler.CodeGeneratorRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CodeGeneratorRequest::CopyFrom(const CodeGeneratorRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobug.compiler.CodeGeneratorRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CodeGeneratorRequest::IsInitialized() const {
  if (!::google::protobug::internal::AllAreInitialized(this->proto_file())) return false;
  return true;
}

void CodeGeneratorRequest::Swap(CodeGeneratorRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CodeGeneratorRequest::InternalSwap(CodeGeneratorRequest* other) {
  using std::swap;
  file_to_generate_.InternalSwap(CastToBase(&other->file_to_generate_));
  CastToBase(&proto_file_)->InternalSwap(CastToBase(&other->proto_file_));
  parameter_.Swap(&other->parameter_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(compiler_version_, other->compiler_version_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobug::Metadata CodeGeneratorRequest::GetMetadata() const {
  protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CodeGeneratorResponse_File::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CodeGeneratorResponse_File::kNameFieldNumber;
const int CodeGeneratorResponse_File::kInsertionPointFieldNumber;
const int CodeGeneratorResponse_File::kContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CodeGeneratorResponse_File::CodeGeneratorResponse_File()
  : ::google::protobug::Message(), _internal_metadata_(NULL) {
  ::google::protobug::internal::InitSCC(
      &protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_CodeGeneratorResponse_File.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobug.compiler.CodeGeneratorResponse.File)
}
CodeGeneratorResponse_File::CodeGeneratorResponse_File(const CodeGeneratorResponse_File& from)
  : ::google::protobug::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  insertion_point_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.has_insertion_point()) {
    insertion_point_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.insertion_point_);
  }
  content_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.has_content()) {
    content_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  // @@protoc_insertion_point(copy_constructor:google.protobug.compiler.CodeGeneratorResponse.File)
}

void CodeGeneratorResponse_File::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  insertion_point_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  content_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

CodeGeneratorResponse_File::~CodeGeneratorResponse_File() {
  // @@protoc_insertion_point(destructor:google.protobug.compiler.CodeGeneratorResponse.File)
  SharedDtor();
}

void CodeGeneratorResponse_File::SharedDtor() {
  name_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  insertion_point_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  content_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

void CodeGeneratorResponse_File::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobug::Descriptor* CodeGeneratorResponse_File::descriptor() {
  ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CodeGeneratorResponse_File& CodeGeneratorResponse_File::default_instance() {
  ::google::protobug::internal::InitSCC(&protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_CodeGeneratorResponse_File.base);
  return *internal_default_instance();
}


void CodeGeneratorResponse_File::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobug.compiler.CodeGeneratorResponse.File)
  ::google::protobug::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      insertion_point_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      content_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CodeGeneratorResponse_File::MergePartialFromCodedStream(
    ::google::protobug::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobug::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobug.compiler.CodeGeneratorResponse.File)
  for (;;) {
    ::std::pair<::google::protobug::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobug::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobug::internal::WireFormat::PARSE,
            "google.protobug.compiler.CodeGeneratorResponse.File.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string insertion_point = 2;
      case 2: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_insertion_point()));
          ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
            this->insertion_point().data(), static_cast<int>(this->insertion_point().length()),
            ::google::protobug::internal::WireFormat::PARSE,
            "google.protobug.compiler.CodeGeneratorResponse.File.insertion_point");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string content = 15;
      case 15: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
            this->content().data(), static_cast<int>(this->content().length()),
            ::google::protobug::internal::WireFormat::PARSE,
            "google.protobug.compiler.CodeGeneratorResponse.File.content");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobug::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobug.compiler.CodeGeneratorResponse.File)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobug.compiler.CodeGeneratorResponse.File)
  return false;
#undef DO_
}

void CodeGeneratorResponse_File::SerializeWithCachedSizes(
    ::google::protobug::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobug.compiler.CodeGeneratorResponse.File)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.File.name");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional string insertion_point = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->insertion_point().data(), static_cast<int>(this->insertion_point().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.File.insertion_point");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->insertion_point(), output);
  }

  // optional string content = 15;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.File.content");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      15, this->content(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobug::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobug.compiler.CodeGeneratorResponse.File)
}

::google::protobug::uint8* CodeGeneratorResponse_File::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobug::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobug.compiler.CodeGeneratorResponse.File)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.File.name");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional string insertion_point = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->insertion_point().data(), static_cast<int>(this->insertion_point().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.File.insertion_point");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        2, this->insertion_point(), target);
  }

  // optional string content = 15;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.File.content");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        15, this->content(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobug::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobug.compiler.CodeGeneratorResponse.File)
  return target;
}

size_t CodeGeneratorResponse_File::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobug.compiler.CodeGeneratorResponse.File)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobug::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 7u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string insertion_point = 2;
    if (has_insertion_point()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::StringSize(
          this->insertion_point());
    }

    // optional string content = 15;
    if (has_content()) {
      total_size += 1 +
        ::google::protobug::internal::WireFormatLite::StringSize(
          this->content());
    }

  }
  int cached_size = ::google::protobug::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CodeGeneratorResponse_File::MergeFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobug.compiler.CodeGeneratorResponse.File)
  GOOGLE_DCHECK_NE(&from, this);
  const CodeGeneratorResponse_File* source =
      ::google::protobug::internal::DynamicCastToGenerated<const CodeGeneratorResponse_File>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobug.compiler.CodeGeneratorResponse.File)
    ::google::protobug::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobug.compiler.CodeGeneratorResponse.File)
    MergeFrom(*source);
  }
}

void CodeGeneratorResponse_File::MergeFrom(const CodeGeneratorResponse_File& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobug.compiler.CodeGeneratorResponse.File)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_insertion_point();
      insertion_point_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.insertion_point_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_content();
      content_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.content_);
    }
  }
}

void CodeGeneratorResponse_File::CopyFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobug.compiler.CodeGeneratorResponse.File)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CodeGeneratorResponse_File::CopyFrom(const CodeGeneratorResponse_File& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobug.compiler.CodeGeneratorResponse.File)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CodeGeneratorResponse_File::IsInitialized() const {
  return true;
}

void CodeGeneratorResponse_File::Swap(CodeGeneratorResponse_File* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CodeGeneratorResponse_File::InternalSwap(CodeGeneratorResponse_File* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  insertion_point_.Swap(&other->insertion_point_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  content_.Swap(&other->content_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobug::Metadata CodeGeneratorResponse_File::GetMetadata() const {
  protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CodeGeneratorResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CodeGeneratorResponse::kErrorFieldNumber;
const int CodeGeneratorResponse::kFileFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CodeGeneratorResponse::CodeGeneratorResponse()
  : ::google::protobug::Message(), _internal_metadata_(NULL) {
  ::google::protobug::internal::InitSCC(
      &protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_CodeGeneratorResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobug.compiler.CodeGeneratorResponse)
}
CodeGeneratorResponse::CodeGeneratorResponse(const CodeGeneratorResponse& from)
  : ::google::protobug::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      file_(from.file_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  error_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
  if (from.has_error()) {
    error_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.error_);
  }
  // @@protoc_insertion_point(copy_constructor:google.protobug.compiler.CodeGeneratorResponse)
}

void CodeGeneratorResponse::SharedCtor() {
  error_.UnsafeSetDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

CodeGeneratorResponse::~CodeGeneratorResponse() {
  // @@protoc_insertion_point(destructor:google.protobug.compiler.CodeGeneratorResponse)
  SharedDtor();
}

void CodeGeneratorResponse::SharedDtor() {
  error_.DestroyNoArena(&::google::protobug::internal::GetEmptyStringAlreadyInited());
}

void CodeGeneratorResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobug::Descriptor* CodeGeneratorResponse::descriptor() {
  ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CodeGeneratorResponse& CodeGeneratorResponse::default_instance() {
  ::google::protobug::internal::InitSCC(&protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::scc_info_CodeGeneratorResponse.base);
  return *internal_default_instance();
}


void CodeGeneratorResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobug.compiler.CodeGeneratorResponse)
  ::google::protobug::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  file_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    error_.ClearNonDefaultToEmptyNoArena();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CodeGeneratorResponse::MergePartialFromCodedStream(
    ::google::protobug::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobug::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobug.compiler.CodeGeneratorResponse)
  for (;;) {
    ::std::pair<::google::protobug::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobug::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string error = 1;
      case 1: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadString(
                input, this->mutable_error()));
          ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
            this->error().data(), static_cast<int>(this->error().length()),
            ::google::protobug::internal::WireFormat::PARSE,
            "google.protobug.compiler.CodeGeneratorResponse.error");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.protobug.compiler.CodeGeneratorResponse.File file = 15;
      case 15: {
        if (static_cast< ::google::protobug::uint8>(tag) ==
            static_cast< ::google::protobug::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobug::internal::WireFormatLite::ReadMessage(
                input, add_file()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobug::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobug.compiler.CodeGeneratorResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobug.compiler.CodeGeneratorResponse)
  return false;
#undef DO_
}

void CodeGeneratorResponse::SerializeWithCachedSizes(
    ::google::protobug::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobug.compiler.CodeGeneratorResponse)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string error = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->error().data(), static_cast<int>(this->error().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.error");
    ::google::protobug::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->error(), output);
  }

  // repeated .google.protobug.compiler.CodeGeneratorResponse.File file = 15;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->file_size()); i < n; i++) {
    ::google::protobug::internal::WireFormatLite::WriteMessageMaybeToArray(
      15,
      this->file(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobug::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobug.compiler.CodeGeneratorResponse)
}

::google::protobug::uint8* CodeGeneratorResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobug::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobug.compiler.CodeGeneratorResponse)
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string error = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobug::internal::WireFormat::VerifyUTF8StringNamedField(
      this->error().data(), static_cast<int>(this->error().length()),
      ::google::protobug::internal::WireFormat::SERIALIZE,
      "google.protobug.compiler.CodeGeneratorResponse.error");
    target =
      ::google::protobug::internal::WireFormatLite::WriteStringToArray(
        1, this->error(), target);
  }

  // repeated .google.protobug.compiler.CodeGeneratorResponse.File file = 15;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->file_size()); i < n; i++) {
    target = ::google::protobug::internal::WireFormatLite::
      InternalWriteMessageToArray(
        15, this->file(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobug::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobug.compiler.CodeGeneratorResponse)
  return target;
}

size_t CodeGeneratorResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobug.compiler.CodeGeneratorResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobug::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .google.protobug.compiler.CodeGeneratorResponse.File file = 15;
  {
    unsigned int count = static_cast<unsigned int>(this->file_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobug::internal::WireFormatLite::MessageSize(
          this->file(static_cast<int>(i)));
    }
  }

  // optional string error = 1;
  if (has_error()) {
    total_size += 1 +
      ::google::protobug::internal::WireFormatLite::StringSize(
        this->error());
  }

  int cached_size = ::google::protobug::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CodeGeneratorResponse::MergeFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobug.compiler.CodeGeneratorResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const CodeGeneratorResponse* source =
      ::google::protobug::internal::DynamicCastToGenerated<const CodeGeneratorResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobug.compiler.CodeGeneratorResponse)
    ::google::protobug::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobug.compiler.CodeGeneratorResponse)
    MergeFrom(*source);
  }
}

void CodeGeneratorResponse::MergeFrom(const CodeGeneratorResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobug.compiler.CodeGeneratorResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobug::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  file_.MergeFrom(from.file_);
  if (from.has_error()) {
    set_has_error();
    error_.AssignWithDefault(&::google::protobug::internal::GetEmptyStringAlreadyInited(), from.error_);
  }
}

void CodeGeneratorResponse::CopyFrom(const ::google::protobug::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobug.compiler.CodeGeneratorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CodeGeneratorResponse::CopyFrom(const CodeGeneratorResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobug.compiler.CodeGeneratorResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CodeGeneratorResponse::IsInitialized() const {
  return true;
}

void CodeGeneratorResponse::Swap(CodeGeneratorResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CodeGeneratorResponse::InternalSwap(CodeGeneratorResponse* other) {
  using std::swap;
  CastToBase(&file_)->InternalSwap(CastToBase(&other->file_));
  error_.Swap(&other->error_, &::google::protobug::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobug::Metadata CodeGeneratorResponse::GetMetadata() const {
  protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::protobug_AssignDescriptorsOnce();
  return ::protobuf_google_2fprotobug_2fcompiler_2fplugin_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace compiler
}  // namespace protobug
}  // namespace google
namespace google {
namespace protobug {
template<> GOOGLE_PROTOBUG_ATTRIBUTE_NOINLINE ::google::protobug::compiler::Version* Arena::CreateMaybeMessage< ::google::protobug::compiler::Version >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobug::compiler::Version >(arena);
}
template<> GOOGLE_PROTOBUG_ATTRIBUTE_NOINLINE ::google::protobug::compiler::CodeGeneratorRequest* Arena::CreateMaybeMessage< ::google::protobug::compiler::CodeGeneratorRequest >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobug::compiler::CodeGeneratorRequest >(arena);
}
template<> GOOGLE_PROTOBUG_ATTRIBUTE_NOINLINE ::google::protobug::compiler::CodeGeneratorResponse_File* Arena::CreateMaybeMessage< ::google::protobug::compiler::CodeGeneratorResponse_File >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobug::compiler::CodeGeneratorResponse_File >(arena);
}
template<> GOOGLE_PROTOBUG_ATTRIBUTE_NOINLINE ::google::protobug::compiler::CodeGeneratorResponse* Arena::CreateMaybeMessage< ::google::protobug::compiler::CodeGeneratorResponse >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobug::compiler::CodeGeneratorResponse >(arena);
}
}  // namespace protobug
}  // namespace google

// @@protoc_insertion_point(global_scope)
